from .UserProps import UserProps
from .ClassProps import ClassProps
from .OwnerProps import OwnerProps
from .CourseProps import CourseProps
from .WalletProps import WallerProps
from .AccountProps import AccountProps
from .StudentProps import StudentProps
from .ClassRelatedCourseProps import ClassRelatedCourseProps
from .StudentRelatedOwnerProps import StudentRelatedOwnerProps