from .IPaymentRepo import IPaymentRepo
from .IUserRepository import IUserRepository
from .IOwnerRepository import IOwnerRepository
from .IAccountRepository import IAccountRepository
from .IStudentRepository import IStudentRepository
from .IStudentAutoRelated import IStudentAutoRelated
from .IClasseRelatedCourse import IClasseRelatedCourseRepository
from .IOwnerRelatedStudentRepository import IOwnerRelatedStudentRepository
